Models/TravelPackage.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace webapp_travel_agency.Models;

public class TravelPackage
{
    public int Id { get; set; }
    
    [Required(ErrorMessage = "Please enter a title")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "Title must be between 3 and 50 characters")]
    public string Title { get; set; }
    
    [Required(ErrorMessage = "Please insert a date")]
    [DataType(DataType.Date)]
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime DepartureDate { get; set; }
    
    [Required(ErrorMessage = "Please insert a date")]
    [DataType(DataType.Date)]
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime ReturnDate { get; set; }
    
    [Required(ErrorMessage = "Please insert a description")]
    [Column(TypeName = "text")]
    public string Description { get; set; }
    
    [Required(ErrorMessage = "Please insert a description")]
    [Column(TypeName = "decimal(6,2)")]
    [Range(0, 50000,ErrorMessage = "Price must be between 0 and 50.000€")]
    public decimal Price { get; set; }
    
    [Required(ErrorMessage = "Please insert a description")]
    [Range(100,500, ErrorMessage = "Place between 100 and 500")]
    public int AvailablePlaces { get; set; }
    
    [Url(ErrorMessage = "Must be a valid URL")]
    public string? UrlImage { get; set; }
    
    [Required(ErrorMessage = "Please insert a destination")]
    public string Destination { get; set; }
}

Controllers/API/TravelPackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using webapp_travel_agency.Context;

namespace webapp_travel_agency.Controllers.API;

[Route("api/packages/")]
[ApiController]
public class TravelPackageController : ControllerBase
{
    private readonly ApplicationDbContext _ctx;

    public TravelPackageController(ApplicationDbContext ctx)
    {
        _ctx = ctx;
    }

    [HttpGet]
    public IActionResult GetAll()
    {
        var travels = _ctx.TravelPackages.ToList();

        if (travels.Count == 0)
        {
            return NotFound();
        }

        return Ok(travels);
    }

    [HttpGet("{id}")]
    public IActionResult Get(int id)
    {
        var travel = _ctx.TravelPackages.FirstOrDefault(x => x.Id == id);

        if (travel == null)
        {
            return NotFound();
        }

        return Ok(travel);
    }
}

Controllers/TravelPackageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using webapp_travel_agency.Context;
using webapp_travel_agency.Models;

namespace webapp_travel_agency.Controllers;

[Authorize]
public class TravelPackageController : Controller
{
    private readonly ApplicationDbContext _ctx;
    
    public TravelPackageController(ApplicationDbContext ctx)
    {
        _ctx = ctx;
    }
    
    [HttpGet]
    public IActionResult Index()
    {
        List<TravelPackage> travels = _ctx.TravelPackages.ToList();
        return View(travels);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(TravelPackage formData)
    {
        if (!ModelState.IsValid)
        {
            return View(formData);
        }
        
        _ctx.TravelPackages.Add(formData);
        _ctx.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var travel = _ctx.TravelPackages.Find(id);
        
        if (travel == null)
        {
            return RedirectToAction("Index");
        }

        return View(travel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(int id, TravelPackage formData)
    {
        if (!ModelState.IsValid)
        {
            return View(formData);
        }
        
        var travel = _ctx.TravelPackages.FirstOrDefault(x => x.Id == id);
        if (travel is null) return RedirectToAction("Index");
        _ctx.TravelPackages.Update(travel);
        _ctx.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(int id)
    {
        var travel = _ctx.TravelPackages.FirstOrDefault(x=>x.Id == id);
        if (travel is null) return RedirectToAction("Index");
        _ctx.TravelPackages.Remove(travel);
        _ctx.SaveChanges();
        return RedirectToAction("Index");
    }
}

Views/TravelPackage/Create.cshtml
@model TravelPackage
@{
    Layout = "_Layout";
}

<div>
    <div class="container">
        <div class="row">
            <div class="col">
                <form method="post" asp-action="Create">
                    @Html.AntiForgeryToken()
                    <div class="mb-3">
                        <label asp-for="Title" for="title" class="form-label">Titolo dell'offerta*</label>
                        <input asp-for="Title" type="text" class="form-control" id="title">
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="DepartureDate" for="departurDate" class="form-label">Departur Date</label>
                        <input asp-for="DepartureDate" type="date" class="form-control" id="departurDate">
                        <span class="text-danger" asp-validation-for="DepartureDate"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ReturnDate" for="returnDate" class="form-label">Return Date</label>
                        <input asp-for="ReturnDate" type="date" class="form-control" id="returnDate">
                        <span class="text-danger" asp-validation-for="ReturnDate"></span>
                    </div>
                    <div class="mb-3 form-check">
                        <label asp-for="Description" class="form-label" for="description">Descrizione</label>
                        <textarea asp-for="Description" id="description" class="form-control"></textarea>
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div>
                        <label asp-for="Price" class="form-label" for="price"></label>
                        <input asp-for="Price" type="number" class="form-control" step="any" id="price"/>€
                        <span class="text-danger" asp-validation-for="Price"></span>
                    </div>
                    <div>
                        <label asp-for="AvailablePlaces" class="form-label" for="availablePlaces"></label>
                        <input asp-for="AvailablePlaces" type="number" class="form-control" step="any" id="availablePlaces"/>€
                        <span class="text-danger" asp-validation-for="AvailablePlaces"></span>
                    </div>
                    <div>
                        <label asp-for="UrlImage" class="form-label" for="urlImage"></label>
                        <input asp-for="UrlImage" type="text" class="form-control" step="any" id="urlImage"/>€
                        <span class="text-danger" asp-validation-for="UrlImage"></span>
                    </div>
                    <div>
                        <label asp-for="Destination" class="form-label" for="destination"></label>
                        <input asp-for="Destination" type="text" class="form-control" step="any" id="destination"/>€
                        <span class="text-danger" asp-validation-for="Destination"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/TravelPackage/Edit.cshtml
@model TravelPackage

@{
    Layout = "_Layout";
}

<div>
    <div class="container">
        <div class="row">
            <div class="col">
                <form method="post" asp-controller="TravelPackage" asp-route-id="@Model.Id" asp-action="Edit">
                    @Html.AntiForgeryToken()
                    <div class="mb-3">
                        <label asp-for="Title" for="title" class="form-label">Titolo dell'offerta*</label>
                        <input asp-for="Title" type="text" class="form-control" id="title">
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="DepartureDate" for="departurDate" class="form-label">Departur Date</label>
                        <input asp-for="DepartureDate" type="date" class="form-control" id="departurDate">
                        <span class="text-danger" asp-validation-for="DepartureDate"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ReturnDate" for="returnDate" class="form-label">Return Date</label>
                        <input asp-for="ReturnDate" type="date" class="form-control" id="returnDate">
                        <span class="text-danger" asp-validation-for="ReturnDate"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Description" class="form-label" for="description">Descrizione</label>
                        <textarea asp-for="Description" id="description" class="form-control"></textarea>
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div>
                        <label asp-for="Price" class="form-label" for="price"></label>
                        <input asp-for="Price" type="number" class="form-control" step="any" id="price"/>
                        <span class="text-danger" asp-validation-for="Price"></span>
                    </div>
                    <div>
                        <label asp-for="AvailablePlaces" class="form-label" for="availablePlaces"></label>
                        <input asp-for="AvailablePlaces" type="number" class="form-control" step="any" id="availablePlaces"/>
                        <span class="text-danger" asp-validation-for="AvailablePlaces"></span>
                    </div>
                    <div>
                        <label asp-for="UrlImage" class="form-label" for="urlImage"></label>
                        <input asp-for="UrlImage" type="text" class="form-control" step="any" id="urlImage"/>
                        <span class="text-danger" asp-validation-for="UrlImage"></span>
                    </div>
                    <div>
                        <label asp-for="Destination" class="form-label" for="destination"></label>
                        <input asp-for="Destination" type="text" class="form-control" step="any" id="destination"/>
                        <span class="text-danger" asp-validation-for="Destination"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/TravelPackage/Index.cshtml
@using Microsoft.AspNetCore.Server.Kestrel.Core
@model List<TravelPackage>

@{
    Layout = "_Layout";
}

@if (@Model.Count <= 0)
{
    <h2>Welcome in your dashboard</h2>
    <p>At moment there isn't no offer, would you add one?</p>
    <a class="btn btn-primary" asp-controller="TravelPackage" asp-action="Create">
        Add an offer
    </a>
}
else
{
    <div class="container">
        <div class="row">
            <div class="col">
                <a class="btn btn-primary" asp-controller="TravelPackage" asp-action="Create">Aggiungi offerta</a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">
                            <a>
                                Offers
                            </a>
                        </th>
                        <th scope="col">Departure Date</th>
                        <th scope="col">Return Date</th>
                        <th scope="col">Price</th>
                        <th scope="col">Available Places</th>
                        <th scope="col">Destination</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var travel in @Model)
                    {
                        <tr>
                            <td>@travel.Id</td>
                            <td>@travel.Title</td>
                            <td>@travel.DepartureDate.ToString("yyyy MMMM dd")</td>
                            <td>@travel.ReturnDate.ToString("yyyy MMMM dd")</td>
                            <td>@travel.Price €</td>
                            <td>@travel.AvailablePlaces</td>
                            <td>@travel.Destination</td>
                            <td class="d-flex">
                                <a class="btn btn-warning" asp-controller="TravelPackage" asp-route-id="@travel.Id" asp-action="Edit">
                                    Edit
                                </a>
                                <form class="d-flex" asp-controller="TravelPackage" asp-action="Delete" asp-route-id="@travel.Id">
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="btn-danger">Elimina</button>
                                </form>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}